### ISSUE TITLE
Navigation Bar 

### ISSUE THREAD

**Issue by MAYJUNE1** [NAXAM/yangmingshan-ios-binding#1]
<img width="364" alt="screen shot 2018-06-05 at 5 04 31 pm" src="https://user-images.githubusercontent.com/39947035/40966242-8c072eb8-68e2-11e8-8a22-2deff4aa9ccb.png">

Does it support iPhone X? Seems like the navigation bar is missing.

**Comment by fleuverouge** [comment]
Hi @MAYJUNE1 Please try out our new Naxam.YangMingShan.iOS.2.0.1.nupkg file.
